# Generated by Django 3.1.6 on 2021-10-12 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='in', max_length=10)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=350)),
                ('sub_title', models.CharField(default='', max_length=150)),
                ('sub_description', models.CharField(default='', max_length=350)),
                ('button', models.CharField(default='', max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Bold text on first page user land -hero-section', max_length=150, verbose_name='HomePage Title')),
                ('description', models.TextField(default='', help_text='description will display on home page below Title -hero-section', max_length=350, verbose_name='HomePage Description')),
                ('background', models.ImageField(default='d.png', help_text='Background Image for home page hero-section', upload_to='home', verbose_name='Home page main banner')),
            ],
        ),
        migrations.CreateModel(
            name='Merged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_img', models.ImageField(default='d.png', upload_to='merged_pic')),
                ('name', models.CharField(default='', max_length=50)),
                ('number', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='eg. Entrepreneurs, Mentors', max_length=150, verbose_name='Segment Title')),
                ('description', models.TextField(default='', help_text='description will display on home page', max_length=350, verbose_name='Segment Description')),
                ('icon', models.ImageField(default='d.png', help_text='icon will display on home page', upload_to='segments', verbose_name='choose icon for segment')),
                ('cta', models.CharField(default='', help_text='This will be the button name on home page', max_length=150, verbose_name='Call to action button name')),
            ],
        ),
        migrations.CreateModel(
            name='Uimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='d.png', upload_to='user_img')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame', models.ImageField(default='d.png', upload_to='frames_pic')),
                ('mask', models.ImageField(default='d.png', upload_to='mask_img')),
                ('frame_heading', models.CharField(default='', max_length=150)),
                ('frame_desc', models.CharField(default='', max_length=350)),
                ('page_title', models.CharField(default='', max_length=150)),
                ('page_desc', models.CharField(default='', max_length=350)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=50)),
                ('percentage', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main.question')),
            ],
        ),
    ]
