# Generated by Django 3.1.6 on 2021-10-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.IntegerField(default=27, help_text='font size to print commitment on image', verbose_name='font size')),
                ('x', models.IntegerField(default=714, help_text='x coordinate to print commitment on image, it helps to decide position', verbose_name='x coordinate')),
                ('y', models.IntegerField(default=634, help_text='y coordinate to print commitment on image, it helps to decide position', verbose_name='y coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='PrintDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.IntegerField(default=20, help_text='font size to print designation on image', verbose_name='font size')),
                ('x', models.IntegerField(default=47, help_text='x coordinate to print designation on image, it helps to decide position', verbose_name='x coordinate')),
                ('y', models.IntegerField(default=677, help_text='y coordinate to print designation on image, it helps to decide position', verbose_name='y coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='PrintImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=369, help_text='x coordinate to print photo on image, it helps to decide position', verbose_name='x coordinate')),
                ('y', models.IntegerField(default=669, help_text='y coordinate to print photo on image, it helps to decide position', verbose_name='y coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='PrintName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.IntegerField(default=25, help_text='font size to print name on image', verbose_name='font size')),
                ('x', models.IntegerField(default=47, help_text='x coordinate to print name on image, it helps to decide position', verbose_name='x coordinate')),
                ('y', models.IntegerField(default=634, help_text='y coordinate to print name on image, it helps to decide position', verbose_name='y coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=40, verbose_name='Form name field')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Form email field')),
                ('designation', models.CharField(default=' ', max_length=40, verbose_name='Form designation field')),
                ('company_name', models.CharField(default=' ', max_length=40, verbose_name='Form Company name field')),
                ('commitment', models.CharField(default='Name', max_length=40, verbose_name='Form Company name field')),
            ],
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='button',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='language_code',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sub_description',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='campaign',
            name='background',
            field=models.ImageField(default='d.png', help_text='icon will display on home page', upload_to='Campaign', verbose_name='background banner image for Campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='commitment_section_description',
            field=models.TextField(default='', help_text='eg. Select the frame and create your custom image to share with the world.', max_length=350, verbose_name='Campaign Sub Description'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='commitment_section_title',
            field=models.CharField(default='', help_text='eg. make a commitment to yourself', max_length=150, verbose_name='Campaign Sub Title'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cta',
            field=models.CharField(default='', help_text='This will be the button name on home page', max_length=150, verbose_name='Call to action button name'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='homepage',
            field=models.ForeignKey(blank=True, default=1, help_text='select the home page within wich these campaign will be displayed.', on_delete=django.db.models.deletion.CASCADE, related_name='campaign', to='main.homepage', verbose_name='homepage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='icon',
            field=models.ImageField(default='d.png', help_text='icon will display on home page', upload_to='Campaign', verbose_name='choose icon for Campaign'),
        ),
        migrations.AddField(
            model_name='frame',
            name='cta',
            field=models.CharField(default='', help_text='This will display under frame image', max_length=150, verbose_name='Call to action button name'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='country_code',
            field=models.CharField(default='in', max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='language_code',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(default='', help_text='description will display on home page', max_length=350, verbose_name='Campaign Description'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(default='', help_text='eg. Entrepreneurs, Mentors', max_length=150, verbose_name='Campaign Title'),
        ),
        migrations.AddField(
            model_name='frame',
            name='print_commitment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.printcommitment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='print_designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.printdesignation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='print_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.printimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='print_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.printname'),
            preserve_default=False,
        ),
    ]
