# Generated by Django 3.1.6 on 2021-09-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='in', max_length=10)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=350)),
                ('sub_title', models.CharField(default='', max_length=150)),
                ('sub_description', models.CharField(default='', max_length=350)),
                ('button', models.CharField(default='', max_length=350)),
            ],
        ),
        migrations.RemoveField(
            model_name='merged',
            name='village',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_desc',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_heading',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='frame',
            name='page_desc',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='frame',
            name='page_title',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=50)),
                ('percentage', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main.question')),
            ],
        ),
        migrations.AddField(
            model_name='frame',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
            preserve_default=False,
        ),
    ]
