# Generated by Django 3.1.6 on 2021-08-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_frame_orientation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='orientation',
        ),
        migrations.RemoveField(
            model_name='merged',
            name='village',
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_desc',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_heading',
            field=models.CharField(default='', max_length=150),
        ),
    ]
