# Generated by Django 3.1.6 on 2021-09-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210815_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='page_desc',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='frame',
            name='page_title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
