# Generated by Django 3.1.6 on 2021-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210901_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='in', max_length=10)),
                ('language_code', models.CharField(default='en', max_length=10)),
                ('title', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=350)),
            ],
        ),
    ]
