# Generated by Django 3.1.6 on 2021-09-01 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.campaign'),
            preserve_default=False,
        ),
    ]
