# Generated by Django 3.1.6 on 2021-09-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210901_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='sub_desc',
            new_name='sub_description',
        ),
    ]
